[package]
name = "lnkhunt"
version = "0.9.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
tempfile = "3.3"


[dependencies.windows]
windows = "0.58.0"
features = [
    "Win32_System_Com",
    "Win32_Foundation",
    "Win32_UI_Shell"
]
